"use client";

import { useRef } from "react";
import { Upload } from "lucide-react";
import { useDockStore } from "@/lib/store";
import { WALLPAPER_PRESETS } from "@/lib/wallpapers";
import { fileToDataUrl } from "@/lib/icons";
import { cn } from "@/lib/utils";

export function WallpaperSelect() {
  const wallpaper = useDockStore((s) => s.wallpaper);
  const setWallpaper = useDockStore((s) => s.setWallpaper);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const onUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    try {
      const dataUrl = await fileToDataUrl(file);
      setWallpaper({ type: "custom", dataUrl });
    } catch (err) {
      console.error("wallpaper upload failed", err);
    } finally {
      e.target.value = "";
    }
  };

  const activePresetId =
    wallpaper.type === "preset" ? wallpaper.id : null;
  const isCustom = wallpaper.type === "custom";

  return (
    <div className="space-y-3">
      <h3 className="text-xs font-semibold uppercase tracking-wide text-white/60">
        Wallpaper
      </h3>

      <div className="grid grid-cols-2 gap-2">
        {WALLPAPER_PRESETS.map((preset) => {
          const active = activePresetId === preset.id;
          return (
            <button
              key={preset.id}
              type="button"
              onClick={() => setWallpaper({ type: "preset", id: preset.id })}
              aria-pressed={active}
              aria-label={`Use ${preset.label} wallpaper`}
              className={cn(
                "group relative aspect-video overflow-hidden rounded-lg border transition-all",
                active
                  ? "border-white/80 ring-2 ring-white/30"
                  : "border-white/10 hover:border-white/40",
              )}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={preset.file}
                alt=""
                className="size-full object-cover"
                draggable={false}
              />
              <span
                className={cn(
                  "absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent px-2 py-1 text-left text-[10px] font-medium",
                  active ? "text-white" : "text-white/80",
                )}
              >
                {preset.label}
              </span>
            </button>
          );
        })}
      </div>

      <input
        ref={fileInputRef}
        type="file"
        accept="image/*"
        onChange={onUpload}
        className="hidden"
      />
      <button
        type="button"
        onClick={() => fileInputRef.current?.click()}
        className={cn(
          "inline-flex w-full items-center justify-center gap-2 rounded-lg border border-dashed px-3 py-2 text-xs font-medium transition-colors",
          isCustom
            ? "border-white/40 bg-white/10 text-white"
            : "border-white/20 bg-white/5 text-white/80 hover:bg-white/10",
        )}
      >
        <Upload className="size-4" />
        {isCustom ? "Custom wallpaper applied" : "Upload custom wallpaper"}
      </button>

      <p className="text-pretty text-[10px] leading-relaxed text-white/40">
        Need something specific? Download wallpapers from{" "}
        <a
          href="https://wallpaperhub.app"
          target="_blank"
          rel="noopener noreferrer"
          className="text-white/65 underline-offset-2 hover:text-white hover:underline"
        >
          wallpaperhub.app
        </a>{" "}
        and upload them here. The presets above are generated by us.
      </p>
    </div>
  );
}
